### ISSUE TITLE
GET /candidates returns only 10 000 results

### ISSUE THREAD

**Issue by FlorentCollin** [oSoc20/solid-elections-api#17]
The GET /candidates endpoint returns only 10 000 results yet there are more than 38 000 results when testing directly in the mandatendatabank. It's certainly due to a limitation of the sparql virtuoso endpoint itself.
The 10 000 results we are having now take already 1.5MB, if by chance we can get around the 10 000 restriction we'll have an endpoint sending a file of 6MB which is simply too big for most connections and just for a search feature in the front end.
One solution to this problem is to let the user first select their party and just after return the list of all candidates in this party. 
This solution works because for now the party with the biggest number of candidates is the N-VA and when querying all members of the N-VA we get a result of approximately 6500 candidates.

Below is the query used to get all members of the N-VA
```sparql
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>
PREFIX mandaat:<http://data.vlaanderen.be/ns/mandaat#>
    SELECT DISTINCT ?firstName ?familyName
    WHERE {
        ?list rdf:type mandaat:Kandidatenlijst ;
        skos:prefLabel "N-VA" ;
        mandaat:heeftKandidaat ?person .
        ?person persoon:gebruikteVoornaam ?firstName ;
        foaf:familyName ?familyName .
}
```

**Comment by juliavdkris** [comment]
I'll have a better look at this tomorrow, but I would think this kind of data should compress pretty well using something like gzip. Not sure about the ratio and if there's an easy way to unzip that data in the frontend though.

Another thing we could do is implement a fuzzy string search (client sends what the user is typing, server returns similar results), but that would probably be a bit more time consuming (a good potential point of improvement to mention in the docs)

**Comment by juliavdkris** [comment]
(The limit can be increased by adding a `VIRT_SPARQL_ResultSetMaxRows` environment variable to your virtuoso stack.yml, I set it to 10.000 on our server)

**Comment by FlorentCollin** [comment]
Fix by increasing the VIRT_SPARQL_ResultSetMaxRows
