### ISSUE TITLE
POST: store should check if the WebID already exists in the DB

### ISSUE THREAD

**Issue by FlorentCollin** [oSoc20/solid-elections-api#4]
In this part of the code, we should verifiy that the WebID doesn't already exist inside the DB.
If the WebID already exists -> do nothing
Else store the new WebID inside the DB
https://github.com/oSoc20/solid-elections-api/blob/206c65ea93a33e5b59bce98a8d5da93d53d41150/src/main.py#L10-L15

**Comment by juliavdkris** [comment]
We can also just make the `uri` field in the WebID class unique (I assume that will throw an exception if you try to insert something with the same value?)
